# Generated by Django 6.0.2 on 2026-03-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='description',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='edition',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='volume',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
