# Generated by Django 6.0.2 on 2026-03-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationRequest',
        ),
    ]
