# Generated by Django 6.0.2 on 2026-03-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_issuedbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
