# Generated by Django 6.0.2 on 2026-03-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_bookrequest_description_bookrequest_edition_and_more'),
        ('transactions', '0004_borrowbook_delete_issuedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='borrow_date',
            field=models.DateField(),
        ),
    ]
