# Generated by Django 6.0.2 on 2026-03-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_bookrequest_description_bookrequest_edition_and_more'),
        ('transactions', '0005_borrowbook_category_alter_borrowbook_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category'),
        ),
    ]
