# Generated by Django 6.0.2 on 2026-03-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_borrowbook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
